# Generated by Django 3.1.4 on 2023-08-31 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_num', models.CharField(max_length=20, verbose_name='CVE number')),
                ('cve_detail', models.CharField(max_length=60, verbose_name='CVE detail')),
                ('project_url', models.CharField(max_length=200, verbose_name='project address')),
                ('project_branch', models.CharField(max_length=50, verbose_name='project branch')),
                ('package', models.CharField(max_length=50, verbose_name='package')),
                ('version', models.CharField(max_length=50, verbose_name='package version')),
                ('maintainer', models.CharField(max_length=100, verbose_name='maintainer')),
                ('email', models.CharField(max_length=100, verbose_name='maintainer email')),
                ('mark', models.IntegerField(choices=[(0, 'not marked'), (1, 'marked')], default=0, verbose_name='mark about whether updated')),
            ],
        ),
    ]
